Improve packing error message for non-meta nested fields.
Previously, trying to pack data with a nested feature that isn't marked as a meta feature would result in `AttributeError: 'dict' object has no attribute 'astype'`. Now it will give a more useful error message along the lines of `Failed to extract segment ids for 'nested_feature', which has type <class 'dict'> rather than np.ndarray. Perhaps it should be marked as a meta feature?`.

PiperOrigin-RevId: 671405450